[package]
name = "gitui"
version = "0.18.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
description = "blazing fast terminal-ui for git"
edition = "2018"
exclude = [".github/*",".vscode/*","assets/*"]
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = [
    "git",
    "gui",
    "cli",
    "terminal",
    "ui",
]

[dependencies]
scopetime = { path = "./scopetime", version = "0.1" }
asyncgit = { path = "./asyncgit", version = "0.18" }
filetreelist = { path = "./filetreelist", version = "0.4" }
crossterm = { version = "0.20", features = [ "serde" ] }
clap = { version = "2.33", default-features = false }
tui = { version = "0.16", default-features = false, features = ['crossterm', 'serde'] }
bytesize = { version = "1.0", default-features = false}
itertools = "0.10"
rayon-core = "1.9"
log = "0.4"
simplelog = { version = "0.10", default-features = false }
dirs-next = "2.0"
crossbeam-channel = "0.5"
scopeguard = "1.1"
bitflags = "1.2"
chrono = "0.4"
backtrace = "0.3"
ron = "0.7"
serde = "1.0"
anyhow = "1.0"
unicode-width = "0.1"
textwrap = "0.14"
unicode-truncate = "0.2"
unicode-segmentation = "1.7"
easy-cast = "0.4"
bugreport = "0.4"
lazy_static = "1.4"
syntect = { version = "4.5", default-features = false, features = ["metadata", "default-fancy"]}
gh-emoji = "1.0.6"
fuzzy-matcher = "0.3"

[target.'cfg(all(target_family="unix",not(target_os="macos")))'.dependencies]
which = "4.1"

# pprof is not available on windows
[target.'cfg(not(windows))'.dependencies]
pprof = { version = "0.5", features = ["flamegraph"], optional = true }

[dev-dependencies]
pretty_assertions = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
default=[]
timing=["scopetime/enabled"]

[workspace]
members=[
    "asyncgit",
    "scopetime",
    "filetreelist",
]

[profile.release]
lto = true
opt-level = 'z'  # Optimize for size.
codegen-units = 1

# make debug build as fast as release 
# usage of utf8 encoding inside tui 
# makes their debug profile slow
[profile.dev.package."tui"]
opt-level = 3

[profile.dev]
split-debuginfo = "unpacked"